.gitignore
flowjax/bijections/utils.py
flowjax/train_utils.py
setup.py

Use batches for computing validation loss (to avoid high memory usage).

Validation batches

---

flowjax/bijections/bnaf.py
flowjax/flows.py

Use square blocks in inner BNAF layers, user now gives the block size as an int.

Improve bnaf parameterisation

---

.gitignore
README.md
flowjax/bijections/abc.py
flowjax/bijections/affine.py
flowjax/bijections/bnaf.py
flowjax/bijections/coupling.py
flowjax/bijections/masked_autoregressive.py
flowjax/bijections/rational_quadratic_spline.py
flowjax/bijections/utils.py
flowjax/distributions.py
flowjax/flows.py
flowjax/train_utils.py
flowjax/utils.py
tests/test_bijections/test_masked_autoregressive.py
tests/test_utils.py

Rudimentary implementation of a [masked autoregressive flow](https://arxiv.org/abs/1705.07057#:~:text=Autoregressive%20models%20are%20among%20the,uses%20internally%20when%20generating%20data.). Works for unconditional density estimation. Still need to implement the inverse bijection (mapping from the base dist to the target), and support conditional density estimation.

Basic implementation of a masked autoregressive flow

---

flowjax/train_utils.py
setup.py
tests/test_train_utils.py

Add option to provide a `filter_spec` to specify trainable parameters.

Filter spec

---

flowjax/bijections/affine.py
flowjax/distributions.py
flowjax/utils.py
tests/test_utils.py

Add broadcasting for distribution arguments.

Distribution broadcasting

---

flowjax/train_utils.py

Add option to provide a `preprocess_bijection` to `train_flow`. e.g. providing `Invert(Affine(x.mean(axis=0), x.std(axis=0)))` would perform standard scaling, and unscale the distribution by transforming the distribution with `Invert(preprocess_bijection)` after training.

Add preprocess bijection

---

README.md
flowjax/bijections/affine.py
flowjax/bijections/transformers.py
flowjax/distributions.py
tests/test_bijections/test_bijections.py
tests/test_distributions.py
tests/test_flows.py

Add weight normalisation for `TraingularAffine`. Also export `StandardNormal` (a standard normal distribution with no trainable parameters).

Triangular weight norm

---

docs/examples/unconditional.ipynb
docs/examples/variational_inference.ipynb
docs/faq.rst
flowjax/distributions.py
flowjax/train/variational_fit.py
tests/test_distributions.py

Switch condition and sample_shape arguments in `Distribution.sample` and `Distribution.sample_and_log_prob`.

Switch sample args

---

flowjax/train/data_fit.py

Previously, if the batch size was greater than the train_len, we errored, and if it was greater than the validation length, then the validation loss would not be computed. Now we instead use min(batch_size, train_size) and min(batch_size, val_size) to set the batch sizes, so no error is thrown, and the validation loss is always computed.

flexible batch_size

---

flowjax/bijections/__init__.py
flowjax/bijections/jax_transforms.py
flowjax/bijections/planar.py
flowjax/flows.py
flowjax/train/losses.py
tests/test_bijections/test_bijections.py

Add planar flow. In the unconditional case, the parameters are learned directly, in the conditional case an MLP conditioner is used to output the parameters.

Planar flow

---

flowjax/train/train_utils.py

This is needed for some optimizers e.g. if they include L2 regularisation.

Pass params in step

---

flowjax/bisection_search.py

Fix bug that sometimes cause an additional step and invalid interval for bisection search

Adapt bisection interval bug fix

---

README.md
flowjax/bisection_search.py
tests/test_bisection_search.py

Handles and adds tests for cases when the bisection search hits the root exactly.

Handle exact solution in bisection search

---

docs/api/experimental.rst
flowjax/experimental/numpyro.py
tests/test_experimental/test_numpyro.py

Add a drop in replacement sample compatible with flowjax and numpyro.

numpyro sample wrapper

---

flowjax/bijections/concatenate.py

fixes #132 (sorry, I should have found this before the previous pull request)

bugfix for concatenate bijection to allow jax tracing

---

.github/workflows/publish.yml

Due to https://github.com/danielward27/flowjax/issues/155

Avoid doctest for now

---

pyproject.toml
tests/test_bijections/test_bijection_utils.py
tests/test_wrappers.py

Update test to use new equinox errors. The tests may still fail due to https://github.com/patrick-kidger/equinox/issues/818.

Test for updated equinox errors

---

flowjax/bisection_search.py

Fixes https://github.com/danielward27/flowjax/issues/173

Avoid array in AutoregressiveBisectionInverter

---

.github/workflows/test.yml
docs/faq.rst
pyproject.toml

Probably better to run tests on earliest supported python version (3.10)

Bump version

---

flowjax/bijections/utils.py
tests/test_bijections/test_bijections.py

Fixes #208. Thanks for the report @amanjitsk

Fix numerical inverse log det

---

flowjax/bijections/__init__.py
flowjax/bijections/bijection.py
flowjax/bijections/chain.py
flowjax/bijections/coupling.py
flowjax/bijections/jax_transforms.py
flowjax/bijections/orthogonal.py
flowjax/bijections/softplus.py
flowjax/bijections/utils.py
flowjax/flows.py
pyproject.toml
tests/test_bijections/test_bijections.py

@aseyboldt I switched the order in ``Sandwich`` arguments to be ``inner, outer``, which felt more intuitive to me. Hope that's OK!

Mostly docs
