danielward27/flowjax

README.md, examples/conditional.ipynb, examples/unconditional.ipynb, flowjax/bijections/transformers.py, tests/test_bijections/test_invertibility.py, tests/test_bijections/test_rational_quadratic_spline.py, tests/test_flows.py
Added Transformer suffix, to avoid potential name clashes between `Bijection`s and `Transformer`s.
=> Transformer suffix added to transformers

flowjax/bijections/utils.py, tests/test_bijections/test_bijection_utils.py, tests/test_flows.py
Prevent error for `intertwine_random_permutation` for 1 layer flows.
=> Fix permutation bug for 1 layer flows

flowjax/train_utils.py
Minor changes to the training script, allowing `val_prop=0`, and avoiding dropping the last batch if it is the same shape as previous batches (not truncated).
=> train_flow update

README.md, flowjax/train_utils.py
Remove option for `preprocess_bijection` as it could potentially cause confusion. For example, a user may expect to be able to run `train_flow` twice in order to train for more epochs (e.g. rerunning a cell containing `train_flow`). However this would not be the case when using a `preprocess_bijection`, as the flow outputted from the first call to `train_flow` would already be transformed by `Invert(preprocess_bijection)`, and the output from the second call would have the inverse transformation applied twice.
Instead, an example is added to the FAQ for scaling/preprocessing, which is more explicit.
=> Remove preprocess and add scaling to FAQ

flowjax/bijections/utils.py, flowjax/flows.py, tests/test_bijections/test_bijection_utils.py
Removed the functions `intertwine_flip` and `intertwine_permute`. Appending bijections (including permutations) within a for loop instead has similar convenience and is arguably clearer.
=> Remove intertwine flip/permute

docs/README.md, flowjax/distributions.py, tests/test_distributions.py
Adds a `sample_and_log_prob` method for `Distribution`. In `Distribution` this relies on `_sample` and `_log_prob` methods separately. However, for `Transformed` distributions, we reimplement it to avoid computing  the inverse transformation.
=> Sample and log prob

.github/workflows/documentation.yml, docs/conf.py, docs/faq.rst, flowjax/train/data_fit.py, flowjax/train/variational_fit.py
Only show types under parameters (not in the signature).
=> Simplify types in docs

README.md, flowjax/distributions.py, flowjax/train/data_fit.py, flowjax/train/losses.py, flowjax/train/train_utils.py, flowjax/train/variational_fit.py, tests/train/test_variational_fit.py
Adds two features:
- ``SpecializeCondition``, to specialise an ammortised conditional distribution to a particular conditioning instance
- ``stick_the_landing`` option in ELBO (a lower variance ELBO estimator) as outlined in https://arxiv.org/abs/1703.09194
Small breaking change:
- Losses are just Callables taking the partitioned model as the first two arguments (see eqx.partition), and we have dropped the ``Loss`` type for now
=> Stick the landing

flowjax/bijections/__init__.py, flowjax/bijections/block_autoregressive_network.py, flowjax/bijections/tanh.py, flowjax/flows.py, flowjax/nn/__init__.py, flowjax/nn/block_autoregressive.py, tests/test_bijections/test_bijections.py, tests/test_bijections/test_bnaf.py
Fixes #102, by using a LeakyTanh bijection, that defaults to a linear transform above or below max_val. Happy for more investigation/discussions, but this seems a reasonable fix for now.
Breaking changes:
- The activation for BlockAutoregressiveNetwork no longer needs a specific form, and instead can be any (potentially trainable) callable or scalar unconditional bijection.
- Renaming of TanhLinearTails to LeakyTanh could break users code (e.g. if subclassing TanhLinearTails, or explicitly relying on the class name).
=> Bnaf Issue

flowjax/train/data_fit.py, flowjax/train/losses.py, flowjax/train/train_utils.py, flowjax/train/variational_fit.py, tests/test_distributions.py
Breaking changes:
- Change in the ``step`` function signature in ``flowjax.train.train_utils``. This was (and still is) undocumented in the API.
- Change in losses signature to always have params first (instead of static). Even in custom loss functions, this often wouldn't break anything as ``eqx.combine`` will usually be symmetric in our use cases i.e. ``combine(pytree1, pytree2)`` will equal ``combine(pytree2, pytree1)``, however, code involving loss functions should be updated to pass them in the right order.
=> Make losses consistent

flowjax/bijections/masked_autoregressive.py, flowjax/nn/masked_autoregressive.py, tests/test_masks.py
Fixes ``jnp.ones`` without dtype specified leading to ``in_ranks`` being float dtype.
=> Ensure int masks and ranks

flowjax/bijections/__init__.py, flowjax/bijections/utils.py, tests/test_bijections/test_bijections.py
Identity bijection. Sometimes useful as a placeholder, or when using `Stack` or `Concatenate` bijections, when we don't want to transform all the inputs.
=> Add identity

.github/workflows/publish.yml
Migrate to using https://docs.pypi.org/trusted-publishers/
=> pypi trusted publishing

flowjax/bijections/affine.py, flowjax/distributions.py, flowjax/flows.py, tests/test_bijections/test_bnaf.py, tests/test_bijections/test_nn.py, tests/test_distributions.py, tests/train/test_data_fit.py
Multivariate normal implemented using a triangular Affine transformation of a standard normal distribution, where the triangular matrix is the cholesky decomposition of the covariance matrix.
=> Multivariate normal

README.md, flowjax/bijections/__init__.py, flowjax/bijections/block_autoregressive_network.py, flowjax/bisection_search.py, flowjax/flows.py, pyproject.toml, tests/test_bisection_search.py
Primary benefit of this is that it allows us to 1) Sample block neural autoregressive flows fitted with maximum likelihood, and 2) evaluate the log probability of  block neural autoregressive flows fitted with variational inference. This can potentially also be used in other flows in the future.
=> Add bisection inverter

docs/api/experimental.rst, flowjax/experimental/numpyro.py, tests/test_experimental/test_numpyro.py
In general, distribution_to_numpyro now replaces TransformedToNumpyro, and now supports non-transformed distributions.
=> Add distribution_to_numpyro

flowjax/bijections/concatenate.py
fixes #130 with the correct splitting indices for Concatenate
=> bugfix for concatenate array splitting

flowjax/bijections/rational_quadratic_spline.py
This modifies RationalQuadraticSpline to apply the spline transformation to all knots, not just the internal ones.
The use case for this is that if the base distribution is defined on a closed interval -- e.g., uniform on [-1, 1] -- the current implementation forces the transformed PDF to match that of the base PDF at the left and right end nodes.
=> end knots transformed by spline instead of identity

flowjax/train/data_fit.py, flowjax/train/variational_fit.py
Adds an option to allow returning the last model, rather than the one which led to the minimum loss. Useful e.g. if loss is high variance to ignore spurious low loss values, or for debugging a model that starts returning nans during training.
=> Option to control returning best parameters vs last parameters in training

flowjax/experimental/numpyro.py, tests/test_experimental/test_numpyro.py
Now when a transformed distribution is converted to a numpyro distribution, it is a numpyro ``TransformedDistribution``, made by seperately wrapping the base distribution and the bijection to the numpyro types. This e.g. facilitates reparameterization of numpyro model.
=> Wrap bijections for converting transformed distributions to numpyro

flowjax/bijections/jax_transforms.py, flowjax/wrappers.py
This replaces two instances of the new `jax.tree` API with the equivalent `jax.tree_util` functions. The former is only available since `jax==0.4.25`, so the other option would be to include `>=0.4.25` in the dependencies.
=> Replace jax.tree API with jax.tree_util for backwards compatibility

flowjax/bijections/rational_quadratic_spline.py
In certain cases, due to numerical instability, the spline transform could map from within [-interval, interval] to outside it. Added clipping so that if x is within the interval, then y is clipped to be within the interval too (and the same for the inverse transform). Outside the interval, the identity transform is still used.
=> Add clipping for numerical stability

docs/faq.rst, flowjax/wrappers.py, pyproject.toml, tests/test_wrappers.py
A likely better way to mark parameters as non_trainable (at the array level rather than the tree level). At the tree level gives a simpler pytree definition, nicer printing etc, but the array level is more robust to avoiding missing attribute errors when e.g. manipulating pytrees.
=> Add non_trainable

flowjax/bijections/planar.py, flowjax/flows.py, tests/test_bijections/test_bijections.py
A first pass on https://github.com/danielward27/flowjax/issues/169.
=> Planar inverse with leaky relu

docs/api/training.rst, docs/api/wrappers.rst, flowjax/bijections/affine.py, flowjax/train/__init__.py, flowjax/wrappers.py, tests/test_wrappers.py
Adds some examples, and slightly simplifies the code. Small breaking change, as the method ``recursive_unwrap`` is removed. For unwrapping all unwrappables ``flowjax.wrappers.unwrap`` should be used.
=> Simplify wrappers

flowjax/train/train_utils.py
The static component can be passed within args. This gives a little more flexibility to users for loss function signature with step (e.g. can ``functools.partial`` out static in loss).
=> No need for static

flowjax/experimental/numpyro.py
Numpyro code still often uses old style keys, so we support it in the wrappers with conversion.
=> Support old style keys in numpyro wrappers

flowjax/bijections/coupling.py, flowjax/bijections/masked_autoregressive.py, flowjax/utils.py, pyproject.toml
Small change so that utils.py does not depend on wrappers.py.
Calls to ``get_ravelled_pytree_constructor`` will now need to explicitly pass the *args and **kwargs for partitioning parameters (usually setting ``is_leaf=lambda leaf: isinstance(leaf, wrappers.NonTrainable)``.
=> Reduce coupling
